language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
  yarn: true
notifications:
  email: false
addons:
  postgresql: "9.6"
services:
  - elasticsearch
  - postgresql
  - redis-server
env:
  global:
    - NODE_ENV=development
    - PORT=5020
    - SEND_MAILS=false
    - FORCE_TEST_END=true
    - SESSION_SECRET=testtest
    - DEFAULT_MAIL_FROM_NAME='travis'
    - DEFAULT_MAIL_FROM_ADDRESS='travis@test.project-r.construction'
    - FRONTEND_BASE_URL=http://localhost:5020
    - LOCAL_ASSETS_SERVER=true
    - ASSETS_SERVER_BASE_URL=http://localhost:5020
    - ASSETS_HMAC_KEY=testtest
    - PARKING_PLEDGE_ID=00000000-1234-0000-0000-000000000001
    - PARKING_USER_ID=00000000-4321-0000-0000-000000000001
    - DISPLAY_AUTHOR_SECRET=testtest
    - AUTO_LOGIN_REGEX='^([a-zA-Z0-9._%+-]+)@test\.project-r\.construction$'
    - DOCUMENTS_RESTRICT_TO_ROLES=member
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.3.0.deb && sudo service elasticsearch restart
before_script:
  # ElasticSearch takes few seconds to start, to make sure it is available
  # when the build script runs add a small delay to your build script
  # see https://docs.travis-ci.com/user/database-setup/#ElasticSearch
  - sleep 10
script:
  - yarn run test:cover
after_success:
  - yarn run test:reportCover
